#!/usr/bin/env bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BLUE}${BOLD}================================${NC}"
echo -e "${BLUE}${BOLD}   GM Assistant Setup${NC}"
echo -e "${BLUE}${BOLD}================================${NC}"
echo ""

# Check prerequisites
if ! command -v docker &>/dev/null; then
  echo -e "${RED}Error: Docker is not installed.${NC}"
  echo "Install Docker: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo -e "${RED}Error: Docker Compose is not available.${NC}"
  echo "Install Docker Compose: https://docs.docker.com/compose/install/"
  exit 1
fi

# Check if .env already exists
if [ -f .env ]; then
  echo -e "${YELLOW}An .env file already exists.${NC}"
  read -rp "Overwrite it? (y/N): " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 0
  fi
  echo ""
fi

# Choose LLM provider
echo -e "${BOLD}Choose your AI provider for generating content:${NC}"
echo ""
echo -e "  1) ${BOLD}Ollama${NC}  - Free, runs locally (needs ~4GB RAM)"
echo -e "  2) ${BOLD}Google${NC}  - Google Gemini (requires API key)"
echo -e "  3) ${BOLD}Anthropic${NC} - Claude (requires API key)"
echo ""
read -rp "Enter choice [1/2/3] (default: 1): " provider_choice

LLM_PROVIDER="ollama"
LLM_MODEL="gemma3:1b"
GOOGLE_AI_API_KEY=""
ANTHROPIC_API_KEY=""

case "$provider_choice" in
  2|google)
    LLM_PROVIDER="google"
    LLM_MODEL="gemini-2.5-flash"
    echo ""
    read -rsp "Enter your Google AI API key: " GOOGLE_AI_API_KEY
    echo ""
    if [ -z "$GOOGLE_AI_API_KEY" ]; then
      echo -e "${RED}Error: API key is required for Google provider.${NC}"
      exit 1
    fi
    echo ""
    read -rp "Model (default: gemini-2.5-flash): " custom_model
    if [ -n "$custom_model" ]; then
      LLM_MODEL="$custom_model"
    fi
    ;;
  3|anthropic)
    LLM_PROVIDER="anthropic"
    LLM_MODEL="claude-sonnet-4-6"
    echo ""
    read -rsp "Enter your Anthropic API key: " ANTHROPIC_API_KEY
    echo ""
    if [ -z "$ANTHROPIC_API_KEY" ]; then
      echo -e "${RED}Error: API key is required for Anthropic provider.${NC}"
      exit 1
    fi
    echo ""
    read -rp "Model (default: claude-sonnet-4-6): " custom_model
    if [ -n "$custom_model" ]; then
      LLM_MODEL="$custom_model"
    fi
    ;;
  *)
    LLM_PROVIDER="ollama"
    echo ""
    read -rp "Model (default: gemma3:1b): " custom_model
    if [ -n "$custom_model" ]; then
      LLM_MODEL="$custom_model"
    fi
    ;;
esac

# Generate secrets
JWT_SECRET=$(openssl rand -base64 48)
SESSION_SECRET=$(openssl rand -base64 48)

# Write .env
cat > .env << ENVEOF
# GM Assistant Configuration
# Generated by setup.sh on $(date -Iseconds)

# Server
NODE_ENV=production
PORT=3000

# Database (Docker internal)
DATABASE_URL=postgresql://gm_user:gm_password@postgres:5432/gm_assistant

# Redis (Docker internal)
REDIS_URL=redis://redis:6379

# S3 Storage (Docker internal)
S3_ENDPOINT=http://minio:9000
S3_BUCKET=gm-assistant
S3_ACCESS_KEY=minio_admin
S3_SECRET_KEY=minio_password

# LLM Provider
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
LLM_BASE_URL=http://ollama:11434
LLM_TIMEOUT=120000
LLM_MAX_TOKENS=4096
LLM_TEMPERATURE=0.7

# Ollama (always required for embeddings)
OLLAMA_BASE_URL=http://ollama:11434

# Google AI API Key
GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}

# Anthropic API Key
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Authentication
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d

# Session
SESSION_SECRET=${SESSION_SECRET}
SESSION_MAX_AGE_DAYS=30
SESSION_UPDATE_AGE_HOURS=1

# OCR Service (Docker internal)
OCR_SERVICE_URL=http://ocr:8080
OCR_TIMEOUT=300000

# CORS
CORS_ORIGIN=http://localhost:3000
ENVEOF

echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo "  LLM Provider: ${LLM_PROVIDER}"
echo "  LLM Model:    ${LLM_MODEL}"
echo "  App URL:      http://localhost:3000"
echo ""
echo -e "To start the application:"
echo ""
echo -e "  ${BLUE}docker compose up${NC}"
echo ""
echo "The first start will take a few minutes to download images and build."
echo -e "Once ready, open ${BOLD}http://localhost:3000/register${NC} in your browser to create an account."
