// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * @gm-assistant/shared
 *
 * Shared type definitions for the GM Assistant API contract.
 * Used by both the frontend client and backend server.
 */

// Common types
export type { Id, ISOTimestamp, BaseEntity } from "./common.js";

// Entity types
export type {
  User,
  AuthUser,
  Session,
  Campaign,
  GenerationSettings,
  DocumentType,
  DocumentStatus,
  DocumentMetadata,
  Document,
  Chunk,
  NpcStatus,
  NpcImportance,
  Npc,
  Location,
  AdventureHookEntity,
  AdventureOutlineEntity,
  AdventureEntity,
  GameSessionStatus,
  GameSession,
  TranscriptSegment,
  TranscriptMarker,
  Transcript,
  SummaryStatus,
  SessionSummary,
  Conversation,
  MessageRole,
  ConversationMessage,
  ConversationWithMessages,
} from "./entities.js";

// Query / RAG types
export type {
  TokenUsage,
  AnswerSource,
  QuerySource,
  QueryFilters,
  ConversationHistoryMessage,
  QueryRequest,
  ConfidenceLevel,
  QueryResponse,
  RAGResult,
} from "./query.js";

// Generation types
export type {
  HookTone,
  GenerateHooksRequest,
  AdventureHook,
  GenerateHooksResponse,
  NpcTone,
  GenerateNpcsRequest,
  GeneratedNpc,
  GenerateNpcsResponse,
  LocationTone,
  GenerateLocationsRequest,
  GeneratedLocation,
  GenerateLocationsResponse,
  GenerationStatusEvent,
  GenerationHookEvent,
  GenerationNpcEvent,
  GenerationLocationEvent,
  GenerationCompleteEvent,
  GenerationErrorEvent,
  GenerationSSEEvent,
  NpcGenerationSSEEvent,
  LocationGenerationSSEEvent,
  OutlineTone,
  GenerateOutlinesRequest,
  OutlineAct,
  GeneratedAdventureOutline,
  GenerateOutlinesResponse,
  GenerationOutlineEvent,
  OutlineGenerationSSEEvent,
  AdventureTone,
  NpcDialogueLine,
  SceneEncounter,
  AdventureScene,
  FactionGoal,
  AdventureFront,
  NodeClue,
  AdventureNode,
  TimelineEntry,
  GenerateAdventureRequest,
  GeneratedAdventure,
  GenerateAdventureResponse,
  GenerationAdventureEvent,
  AdventureGenerationSSEEvent,
} from "./generation.js";

// API request/response types
export type {
  ApiErrorResponse,
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  AuthResponse,
  LoginMfaChallengeResponse,
  LoginResponse,
  MfaLoginRequest,
  MfaSetupResponse,
  MfaEnableRequest,
  MfaEnableResponse,
  MfaDisableRequest,
  CreateCampaignRequest,
  UpdateCampaignRequest,
  CampaignResponse,
  CampaignListResponse,
  CampaignStatsResponse,
  DocumentListQuery,
  UpdateDocumentRequest,
  DocumentResponse,
  DocumentListResponse,
  DocumentDownloadResponse,
  CreateNpcRequest,
  UpdateNpcRequest,
  NpcListQuery,
  NpcResponse,
  NpcListResponse,
  CreateLocationRequest,
  UpdateLocationRequest,
  LocationListQuery,
  LocationResponse,
  LocationListResponse,
  CreateAdventureHookRequest,
  UpdateAdventureHookRequest,
  AdventureHookListQuery,
  AdventureHookResponse,
  AdventureHookListResponse,
  CreateAdventureOutlineRequest,
  UpdateAdventureOutlineRequest,
  AdventureOutlineListQuery,
  AdventureOutlineResponse,
  AdventureOutlineListResponse,
  ConversationListResponse,
  ConversationDetailResponse,
  CreateConversationRequest,
  CreateConversationResponse,
  CreateAdventureRequest,
  UpdateAdventureRequest,
  AdventureListQuery,
  AdventureResponse,
  AdventureListResponse,
  GameSessionListQuery,
  GameSessionResponse,
  GameSessionListResponse,
  TranscriptResponse,
  SessionSummaryResponse,
  SessionAudioResponse,
  UpdateSessionSummaryRequest,
  CreateMarkerRequest,
  UpdateMarkerRequest,
  MarkerResponse,
  MarkersResponse,
  MarkerWithContext,
  MarkersWithContextResponse,
  SupportedAudioMimeType,
  SupportedMimeType,
} from "./api.js";

// Runtime values
export { SUPPORTED_MIME_TYPES, SUPPORTED_AUDIO_MIME_TYPES } from "./api.js";
